version: '2.1'
services:
  xdag-proxy:
    container_name: xdag-proxy
    image: nginx:1.12
    ports:
      - "80:80"
    depends_on:
      - xdag-pool
      - xdag-mysql
    volumes:
      - ./xdag-proxy/container-files/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - xdag-pool
  xdag-pool:
    container_name: xdag-pool
    image: melthaw/xdag:latest
    depends_on:
      - xdag-mysql
    links:
      - xdag-mysql:mysql
#    ports:
#      - "9000:9000"
  xdag-mysql:
    container_name: xdag-mysql
    image: mariadb:10.3.7
    ports:
      - "3306:3306"
    volumes:
      - ~/var/xdag/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
